- docs/components/metadata/stats.md
HitStats example didn’t work, it used this.getHitsCount() instead of this.searchkit.getHitsCount()
> fix HitsStats codepen example

- src/components/search/pagination/src/Pagination.tsx
- src/components/search/pagination/styles/index.scss
- src/components/search/pagination/test/PaginationSpec.tsx
- src/core/SearchkitManager.ts
- src/core/accessors/StatefulAccessor.ts
Pagination : add page numbers
Fixes #40 
New props : showNumbers and pageScope (number of page numbers to show before and after the current one)
WIP version, adds page numbers.
Props: showNumbers and pageScope
Missing disabled ‘…’ when there are too many pages (previous, 1, …, 5,
6, 7, 8, 9, …, 147, next)
Use links for pagination buttons
Added SearchkitManager.buildSearchUrl(extraParams) to create new urls
with different parameters
Pagination buttons are now links
Move url building to accessor
Pagination : show ellipsis on page ranges
Add Pagination tests and fix showNumbers prop
> Add page numbers to pagination and corresponding tests

- src/core/react/SearchkitComponent.ts
> SearchkitComponent's contextTypes should be a React.ValidationMap<any>

- src/components/index.ts
- src/components/search/filters/input-filter/InputFilter.tsx
- src/components/search/search-box/src/SearchBox.tsx
- src/core/AccessorManager.ts
- test/e2e/server/apps/playground/index.tsx
- theming/components.scss
- theming/components/_input-filter.scss
- tsconfig.json
Simple test to see if multiple searchboxes could be used.
The only change is to have a default `id="q"` for the searchbox, and consider that one as the default query accessor. Extra searchboxes can be added and used as filters.
Tested be adding another one in the facet sidebar : 
```jsx
<SearchBox id="author_q" 
autofocus={false} 
searchOnChange={true} 
prefixQueryFields={["actors"]} 
queryFields={["actors"]}/>
```
Works well (minus CSS styling)
> [WIP] multi-searchbox (will be converted to InputFilter)

- package.json
Missing dependency results in `protractor not found` when running `npm run test:e2e`
> add protractor to dev deps

- docs/setup/elasticsearch.md
Added link to Elastic Cloud (formerly known as Found), a hosted and managed Elasticsearch service from Elastic, the company behind Elasticsearch, Logstash, Kibana and Beats. 
I don't want to suggest that you should promote any particular service, so please feel free to re-order. Alphabetical ordering might be the most fair? :)
> Add Elastic Cloud as hosted Elasticsearch provider

- src/__test__/core/accessors/FacetAccessorSpec.ts
- src/core/accessors/FacetAccessor.ts
This is a really simple fix for a minor bug where the View more/all link sometimes doesn't appear below a refinement list filter.
There was an edge case where `this.size + facetsPerPage == total` - this slips in between the 'view all' and 'view more' options, and therefore neither was shown. This commit just ensures the 'View All' link is shown in this case.
> Fix FacetFilter 'View All' link edge case

- docs/components/navigation/menu.md
- docs/components/navigation/refinement-list.md
- src/__test__/core/accessors/FacetAccessorSpec.ts
- src/components/search/filters/facet-filter/FacetFilter.tsx
- src/components/search/filters/facet-filter/FacetFilter.unit.tsx
- src/components/search/filters/facet-filter/FacetFilterProps.ts
- src/components/search/filters/facet-filter/MenuFilter.unit.tsx
- src/core/accessors/FacetAccessor.ts
- Inject missing selected filters to the top of a category
- add bucketsTransform property to RefinementList + Menu
- Replicate by selecting a facet + using search input box
> inject missing selected filters

- docs/server/indexing.md
> Fix broken markdown in indexing documentation

- theming/components/_filter-item.scss
When filter option name is too long, checkbox shouldn't shrink
Currently, checkbox shrinks for long category names:
> Checkbox should be fixed size

- src/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter.tsx
- src/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec.tsx
issue #391 spotted that if a size is not specified, its default is 0 which in ES5 now is invalid. This small update defaults it to 20.
> Hierarchical Menu filter size has a default of 20 

- src/__test__/core/SearchkitManagerSpec.ts
- src/__test__/core/transport/AxiosESTransportSpec.ts
- src/core/transport/AxiosESTransport.ts
This is needed when your elasticsearch cluster is running with basic auth under a different domain: https://developer.mozilla.org/pt-BR/docs/Web/API/XMLHttpRequest/withCredentials.
I also changed the code to use the basic auth functionality exposed by axios instead of reimplementing it.
This is the code draft, happy to improve tests if the code is in the right direction.
> Add withCredentials support

- src/components/ui/list/ListProps.ts
- src/components/ui/range/RangeProps.ts
- src/components/ui/range/RangeSlider.tsx
This fixes the following problems when consuming searchkit in typescript:
````
Error in /Users/davi/code/my-app/node_modules/searchkit/lib/src/components/ui/range/RangeSlider.d.ts
(8,23): error TS7006: Parameter 'number' implicitly has an 'any' type.
Error in /Users/davi/code/my-app/node_modules/searchkit/lib/src/components/ui/range/RangeProps.d.ts
(20,18): error TS7006: Parameter 'string' implicitly has an 'any' type.
Error in /Users/davi/code/my-app/node_modules/searchkit/lib/src/components/ui/list/ListProps.d.ts
(12,18): error TS7006: Parameter 'string' implicitly has an 'any' type.
````
> Fix inline parameters declaration syntax.

- package.json
See https://github.com/searchkit/searchkit/issues/410.
> Move jasmine types to devDependencies.

- docs/components/navigation/hierarchical-refinement-filter.md
- src/__test__/core/accessors/NestedFacetAccessorSpec.ts
- src/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter.tsx
- src/components/search/filters/hierarchical-refinement-filter/test/HierarchicalRefinementFilterSpec.tsx
- src/core/accessors/NestedFacetAccessor.ts
- src/core/query/query_dsl/aggregations/BucketAggregations.ts
fixes issue where nestedAccessor is 0 by default causing an issue for ES5. Affects Nested Filter. This is a merge of @juan-fdz-hawa  #429 changes
> aggregation size cannot be 0 by default

- docs/components/navigation/hierarchical-menu.md
Updated the hierarchical menu docs page so that the code sample used consistent field names throughout; since it caused some confusion for a colleague recently.
With Elasticsearch 5 now released I was going to try to address the fact that [the `"string"` data type the docs recommend has been removed](https://www.elastic.co/blog/strings-are-dead-long-live-strings), but wasn't sure the best way to approach that. Happy to update this PR with a bit of guidance there.
In Elasticsearch 5.5.0 where string has been removed, I found that if no explicit mapping is created but data gets pushed in with the form:
```
"category": {
"lvl1": "Appliances" 
"lvl2": "Air Conditioners"
"lvl3": "Window Air Conditioners"
}
```
The component functions fine if directed to the fields:
``` …
```
> Hierarchical Menu Docs

- src/__test__/core/query/ImmutableQuerySpec.ts
- src/core/query/query_dsl/aggregations/BucketAggregations.ts
This should prevent the warnings in issue #423.
Suppressing the `filters: {}` clause will not work. Therefore, it no filters are found, it is replace with the `match_all: {}` filter.
Tested this successfully in an own application.
> Issue 423: prevent deprecation warning by replacing empty filter with match_all

- docs/setup/default-query.md
Using this example with ES5 was returning an error from the server.
> Fix default query example for ES5

- src/__test__/core/query/ImmutableQuerySpec.ts
- src/__test__/core/query/query_dsl/aggregations/BucketAggregationsSpec.ts
- src/core/query/query_dsl/aggregations/BucketAggregations.ts
I've used these two bucket aggregations in a private project for some time and thought it'd be nicer to have them directly in SearchKit.  This would fix isse #427.
> Issue 427: add DateHistogramBucket and GeoboundsBucket aggregations

- docs/components/basics/hits.md
- docs/core/SearchkitManager.md
- src/__test__/core/AccessorManagerSpec.ts
- src/__test__/core/SearchkitManagerSpec.ts
- src/__test__/core/react/SearchkitComponentSpec.tsx
- src/components/search/filters/checkbox-filter/CheckboxFilter.unit.tsx
- src/components/search/filters/dynamic-range-filter/DynamicRangeFilter.unit.tsx
- src/components/search/filters/facet-filter/FacetFilter.unit.tsx
- src/components/search/filters/facet-filter/MenuFilter.unit.tsx
- src/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec.tsx
- src/components/search/filters/hierarchical-refinement-filter/test/HierarchicalRefinementFilterSpec.tsx
- src/components/search/filters/input-filter/InputFilter.unit.tsx
- src/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec.tsx
- src/components/search/filters/range-filter/test/RangeFilterSpec.tsx
- src/components/search/filters/tag-filter/TagFilter.unit.tsx
- src/components/search/filters/tag-filter/TagFilterList.unit.tsx
- src/components/search/hits/src/Hits.tsx
- src/components/search/hits/test/HitsSpec.tsx
- src/components/search/search-box/Searchbox.unit.tsx
- src/components/search/sorting-selector/test/SortSelectorSpec.tsx
- src/core/AccessorManager.ts
- src/core/SearchkitManager.ts
- test/e2e/server/apps/movie-app/index.tsx
- shouldPerformSearch can be overriden to control if searchkit runs searches
- Searchkit now defaults size, so doesn't rely on hitsPerPage in Hits component to work
#330 #537
> Add shouldPerformSearch check, add defaultSize

- packages/searchkit/package.json
- packages/searchkit/src/__test__/core/history/HistorySpec.ts
- packages/searchkit/src/__test__/core/react/SearchkitProviderSpec.tsx
- packages/searchkit/src/core/history.ts
- packages/searchkit/src/core/react/SearchkitProvider.tsx
- reset searchkit guidCounter on provider unmount, which allows searchkit state to be reconstructed with routers
- detect if history is supported and provide correct implementation, convenience for running on node.js
> History + Guid fixes

- packages/searchkit/src/core/accessors/SuggestionsAccessor.ts
`_all` field is deprecated in ES 6.0.0. See https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-all-field.html
As such, `direct_generator`, referenced in `SuggestionsAccessor`, is no longer operational. This PR  adresses this, by using directly the current field instead. Since there is no longer a standard catchall field, keeping the generation on a catchall field was not possible.
> Replace deprecated _all in SuggestionsAccessor

- packages/searchkit/src/core/SearchkitManager.ts
- packages/searchkit/src/core/history.ts
```
window is not defined
ReferenceError: window is not defined
at Object.exports.supportsHistory (/node_modules/searchkit/src/core/history.ts:13:12)
```
> window is undefined on server side, fixed invalid logic in SSR support

- CHANGELOG.md
We upgraded from 2.1.0 to 2.3.0 and it took us a while to understand why the requests sent from searchkit to our backend look like this:
```json
{
"post_filter": {
"term": {
"undefined": "brands"
}
},
"aggs": {
"_type3": {
"filter": {
"term": {
"undefined": "brands"
}
},
"aggs": {
"undefined": {
"terms": {}
},
"undefined_count": {
"cardinality": {}
}
}
}
}
}
```
I had to check the commits one by one, from 2.1.0 to get the to this change: https://github.com/searchkit/searchkit/commit/d7f9eab70bc9b87f91f2122ecf1667a13f1b6a0e#diff-f172a23508b6de00b38c007df825d91a
So I think it might save someone else's time to mention the breaking change in the change log file
thanks :)
> Add 2.3.0 to changelog.md & mention the breaking change in FacetFilter

- packages/searchkit/src/__test__/core/react/SearchkitComponentSpec.tsx
- packages/searchkit/src/__test__/core/react/SearchkitProviderSpec.tsx
- packages/searchkit/src/components/display/view-switcher/ViewSwitcherHits.tsx
- packages/searchkit/src/components/search/filters/checkbox-filter/CheckboxFilter.tsx
- packages/searchkit/src/components/search/filters/dynamic-range-filter/DynamicRangeFilter.tsx
- packages/searchkit/src/components/search/filters/facet-filter/FacetFilter.tsx
- packages/searchkit/src/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter.tsx
- packages/searchkit/src/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter.tsx
- packages/searchkit/src/components/search/filters/input-filter/InputFilter.tsx
- packages/searchkit/src/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter.tsx
- packages/searchkit/src/components/search/filters/range-filter/src/RangeFilter.tsx
- packages/searchkit/src/components/search/filters/reset-filters/src/ResetFilters.tsx
- packages/searchkit/src/components/search/hits/src/Hits.tsx
- packages/searchkit/src/components/search/hits/src/NoHits.tsx
- packages/searchkit/src/components/search/pagination/src/Pagination.tsx
- packages/searchkit/src/components/search/search-box/SearchBox.tsx
- packages/searchkit/src/components/search/sorting-selector/src/SortingSelector.tsx
- packages/searchkit/src/core/react/SearchkitComponent.ts
- packages/searchkit/src/core/react/SearchkitProvider.tsx
This PR should make Searchkit work with React 16.4+, however it does introduce breaking change in that the accessor is not guaranteed to be present on initial render. It's the only way to have accessor work since componentwillmount is not syncronous anymore, so you have to rely on renders.
> Updated searchkit to work with React 16.4

- packages/searchkit/src/core/accessors/FacetAccessor.ts
Prior to ES 6, boolean values could be queried with '0' or '1' instead of 'false' or 'true'. This PR will query with 'false' or 'true' for ES 6. It implements the solution proposed in the issue opened here: https://github.com/searchkit/searchkit/issues/655
> query with true or false rather than 1 or 0 for boolean values

- packages/searchkit/src/components/search/search-box/SearchBox.tsx
- packages/searchkit/src/components/search/search-box/Searchbox.unit.tsx
```
Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
in input (created by SearchBox)
in form (created by SearchBox)
in div (created by SearchBox)
in SearchBox (created by App)
in div
in Unknown (created by App)
in SearchkitProvider (created by App)
in App
```
I didnt find official documentation, but this old merged pr https://github.com/facebook/react/pull/4003
says 
```
For <input> and <textarea>, onChange supersedes — and should generally be used instead of — the DOM's built-in oninput event handler.
```
React version
"react": "^16.6.3",
"react-dom": "^16.6.3",
> fix warning "You provided a `value` prop to a form field without an `onChange` handler"

- packages/searchkit-autosuggest/package.json
- packages/searchkit-refinement-autosuggest/package.json
- packages/searchkit/package.json
- yarn.lock
Don't pin lodash to remove duplicate lodash version and to be able to use only one updated version of lodash in my project instead of two.
> don't pin lodash to avoid duplicates

- packages/searchkit/src/components/search/hits/src/Hits.tsx
Prevent errors in case when `$all` `_index` has results with same `_id`
Closes #711
> Make HitsList item key more unique

- packages/searchkit-refinement-autosuggest/src/RefinementAutosuggestAccessor.ts
- packages/searchkit-refinement-autosuggest/src/adapters/react-select/ReactSelectAdapter.tsx
I was porting your **searchkit-autosuggest-package** and noticed that some of your import entries are not used: one of them definitely is moved to Utils.
So I decided to remove it from sources.
> Remove unused imports

- packages/searchkit/src/components/search/pagination/src/Pagination.tsx
utilize getHitsCount() method in getTotalPages.
Fixes bug that prevented pages from being displayed when `showNumbers={true}` was enabled in the `Pagination` component. #732
> Use getHitsCount() in getTotalPages()

- packages/searchkit/src/__test__/core/accessors/NumericalOptionsAccessorSpec.ts
- packages/searchkit/src/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec.tsx
- packages/searchkit/src/core/accessors/NumericOptionsAccessor.ts
When we use `NumericRefinementListFilter` as single select. Then, it is not possible to deselect already selected option.
This pull request will allow deselection of already selected option.
> Allowed option deselection in NumericRefinementListFilter when using single select

- packages/searchkit-docs/docs/setup/project-setup.md
I'm just guessing what the correct link should be here. If this isn't it, it should probably just be removed.
Also, please use HTTPS links.
> Update dead link to searchkit-boilerplate project

- docs/docs/guides-indexing.md
This link was missing a protocol, making it a relative link to `https://searchkit.co/docs/guides/www.qbox.io?ref=searchkit` instead of  `www.qbox.io?ref=searchkit`.
> Fix link to qbox.io

- packages/searchkit-cli/src/lib.ts
- packages/searchkit-schema/README.md
- packages/searchkit-schema/src/core/SearchkitRequest.ts
- packages/searchkit-schema/src/resolvers/HitsResolver.ts
- packages/searchkit-schema/src/resolvers/ResultsResolver.ts
- packages/searchkit-schema/tests/HitsResolver.test.ts
- packages/searchkit-schema/tests/__mock-data__/HitResolver/HighlightHits.json
- packages/searchkit-schema/tests/__snapshots__/HitsResolver.test.ts.snap
- packages/searchkit-schema/tests/support/helper.ts
- packages/searchkit-schema/tests/support/server.ts
Implements feature discussed in https://github.com/searchkit/searchkit/issues/879
Setting highlightedFields in Searchkit config plus a customized ResultHit
graphql type and custom resolver one can request ElasticSearch to generate
highlights for matched words and expose it via graphql to the searchkit
clients.
Resolvers for custom ResultHit fields will receive the highlights in the
"highlight" property, but also added a "rawHit" field containing the hit
record as received from ES, which may come handy in other use cases.
Note: I had to refact `setupTestServer` so that I could add custom graphql typedefs
and resolver to my test, hope it is OK.
> feat: Add highlight support for matched words

- CHANGELOG.md
- docs/docs/guides-ssr.md
- examples/next/components/searchkit/Hits.jsx
- examples/next/hocs/withApollo.js
- examples/next/pages/index.jsx
- lerna.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-client/src/__tests__/components.test.tsx
- packages/searchkit-client/src/searchkit.tsx
- packages/searchkit-client/src/withSearchkitRouting.tsx
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
- packages/searchkit-schema/CHANGELOG.md
- packages/searchkit-schema/package.json
- Bug fix: search was not called on client side render, therefore variables contained the baseState only even though the url contains searchState.
- Bug fix: Issue with sortBy being either null or not provided in variables causing a miss in apollo cache and resulting in a XHR request to server on client hydrate
> Release 35

- docs/docs/api-setup.md
If you copy-paste the whole block into your `graphql.js` definition, you're getting an error `GraphQLError [Object]: Syntax Error: Cannot parse the unexpected character "/".`. Replacing the comment with `#` fixes the issue.
> // is not a valid comment in GraphQL

- CHANGELOG.md
- docs/docs/searchkit-sdk.md
- lerna.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
- packages/searchkit-schema/CHANGELOG.md
- packages/searchkit-schema/package.json
- packages/searchkit-sdk/CHANGELOG.md
- packages/searchkit-sdk/package.json
- packages/searchkit-sdk/src/index.ts
- packages/searchkit-sdk/tests/__snapshots__/sortBy.test.ts.snap
- packages/searchkit-sdk/tests/sortBy.test.ts
fixes #1093 
Allows a default sort option to be used when no sort is specified. 
```
sortOptions: [
{id: 'relevance', label: 'Relevance', field: '_score'},
{
id: 'released',
label: 'Recent Releases',
field: {released: 'desc'},
defaultOption: true,
},
{
id: 'title-released',
label: 'Recent titles',
field: [{released: 'desc'}, {title: 'desc'}],
},
{
id: 'multiple_sort',
label: 'Multiple sort',
field: [
{post_date: {order: 'asc'}},
'user',
{name: 'desc'},
{age: 'desc'},
'_score',
],
},
],```
> Allow default sorting option

- examples/next/components/geosearch-examples/maps.jsx
- packages/searchkit-cli/src/lib.ts
- packages/searchkit-client/src/searchkit.tsx
- packages/searchkit-sdk/src/core/RequestBodyBuilder.ts
- packages/searchkit-sdk/src/facets/DateRangeFacet.ts
- packages/searchkit-sdk/src/facets/HierarchicalMenuFacet.ts
- packages/searchkit-sdk/src/facets/MultiQueryOptionsFacet.ts
- packages/searchkit-sdk/src/facets/RangeFacet.ts
- packages/searchkit-sdk/src/filters/GeoBoundingBoxFilter.ts
- packages/searchkit-sdk/src/filters/NumericRangeFilter.ts
This changes lodash imports to direct import statements and helps projects using searchkit to reduce their bundle size.
Importing as whole like `import _ from 'lodash'` can lead to large bundle sizes, because tree shaking is not possible.
> import lodash methods

- docs/docs/searchkit-elastic-ui.mdx
Just adding actual video instead of references for better experience. Renamed .md => .mdx for better default syntax highlighting.
> Embedding videos for searchkit-elastic-ui.mdx

- docs/docs/searchkit-sdk-autocomplete.mdx
- packages/searchkit-sdk/src/index.ts
- packages/searchkit-sdk/src/query/PrefixQuery.ts
- packages/searchkit-sdk/src/query/index.ts
- packages/searchkit-sdk/src/suggestors/CompletionSuggestor.ts
- packages/searchkit-sdk/src/suggestors/HitsSuggestor.ts
- packages/searchkit-sdk/src/suggestors/index.ts
- packages/searchkit-sdk/src/transporters/FetchClientTransporter.ts
- packages/searchkit-sdk/src/transporters/index.ts
- packages/searchkit-sdk/tests/__mock-data__/suggestors/Completion.json
- packages/searchkit-sdk/tests/__mock-data__/suggestors/Hits.json
- packages/searchkit-sdk/tests/suggestions/CompletionSuggestor.test.ts
- packages/searchkit-sdk/tests/suggestions/HitsSuggestor.test.ts
This feature will enable building components for autocomplete features within searchkit. First step is to enable SDK to configure and perform getting suggestions.
> Searchkit Suggestors support 

- docs/docs/searchkit-sdk-core.mdx
- examples/next/package.json
- package.json
- packages/searchkit-cli/package.json
- packages/searchkit-client/package.json
- packages/searchkit-schema/package.json
- packages/searchkit-sdk/package.json
- packages/searchkit-sdk/src/index.ts
- packages/searchkit-sdk/src/transporters/ESClientTransporter.ts
- packages/searchkit-sdk/src/transporters/FetchClientTransporter.ts
- packages/searchkit-sdk/src/transporters/__tests__/ESClientTransporter.test.ts
- packages/searchkit-sdk/src/transporters/__tests__/FetchClientTransporter.test.ts
- packages/searchkit-sdk/src/transporters/utils.ts
- yarn.lock
When your elasticsearch instance is hosted on [cloud.elastic.co](https://cloud.elastic.co), you can use the `cloudId` to connect to it.
```javascript
const searchkitConfig = {
cloud: {
id: 'commerce-demo:dXMtZWFzdDQuZ2NwLmVsYXN0aWMtY2xvdWQuY29tOjQ0MyRkMWJkMzY4NjJjZTU0YzdiOTAzZTJhYWNkNGNkN2YwYSQ2ZDRiY2YwOWI2ZWU0NjBjOWVlNTg4YjJiNWM5ZGE0MQ==', // elastic cloud id
},
connectionOptions: {
apiKey: "<api-key>"
},
index: 'movies',
hits: { fields: [ 'title', 'plot', 'poster' ] },
query: new MultiMatchQuery({
fields: [ 'plot','title^4'],
highlightFields: ["title"]
})
}
const request = Searchkit(config) 
const response = await request 
.query("heat")
```
> Cloud id support

- .changeset/wise-snakes-double.md
- apps/web/pages/docs/api-documentation/api.mdx
- apps/web/pages/docs/guides/_meta.json
- apps/web/pages/docs/guides/customising-query.mdx
- apps/web/pages/docs/guides/learn-to-rank.mdx
- apps/web/pages/index.mdx
- packages/searchkit-api/src/___tests___/functional/__snapshots__/hooks.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/hooks.test.ts
- packages/searchkit-api/src/index.ts
- packages/searchkit-api/src/types.ts
Implement optional methods to allow developer to add logic to transform the elasticsearch request and the elasticsearch response.
> V4: beforeSearch / afterSearch Hooks support

- .changeset/chilled-birds-repair.md
- apps/web/pages/docs/guides/query-rules.mdx
- packages/searchkit-api/src/___tests___/functional/__snapshots__/filters.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/getFilters.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/getQuery.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/hitsPerPage.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/hooks.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/index.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/nestedFacets.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/queryRules.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/relevance.test.ts.snap
- packages/searchkit-api/src/___tests___/transformRequest.test.ts
- packages/searchkit-api/src/queryRules.ts
- packages/searchkit-api/src/transformResponse.ts
Query Rules: Expose rule ids in API in Search Response
> Query Rules: Expose rule ids in API in Search Response

- .changeset/giant-carrots-shout.md
- .vscode/launch.json
- apps/web/package.json
- apps/web/pages/api/config.ts
- apps/web/pages/browser-only-demo.jsx
- apps/web/pages/demos.mdx
- apps/web/pages/docs/api-documentation/instantsearch-client.mdx
- packages/searchkit-instantsearch-client/jest.config.js
- packages/searchkit-instantsearch-client/package.json
- packages/searchkit-instantsearch-client/src/index.ts
- packages/searchkit-instantsearch-client/test/APIClient.test.ts
- packages/searchkit-instantsearch-client/test/__snapshots__/APIClient.test.ts.snap
- packages/searchkit-instantsearch-client/test/__snapshots__/browserOnly.test.ts.snap
- packages/searchkit-instantsearch-client/test/browserOnly.test.ts
- packages/searchkit-instantsearch-client/tsconfig.json
You can also use the client to directly query Elasticsearch from the browser, skipping needing a node API in the middle. This is useful if you're proxying the Elasticsearch API through your own application API.
> Instantsearch-client: Browser only support

- .changeset/yellow-mangos-yawn.md
- packages/searchkit/src/___tests___/filters.test.ts
- packages/searchkit/src/filters.ts
Fixes an issue in `transformNumericFilters` where negative values were rejected - e.g. `discount<-10` and adds support for the numeric range format detailed here: https://www.algolia.com/doc/api-reference/api-parameters/numericFilters/#numeric-range
> feat: add support for negative numbers and numeric ranges

- .changeset/calm-comics-love.md
- apps/web/pages/docs/api-documentation/searchkit.mdx
- apps/web/pages/docs/getting-started/with-react.mdx
- apps/web/pages/docs/guides/customising-query.mdx
- packages/searchkit/package.json
- packages/searchkit/src/___tests___/functional/KNNSearch.test.ts
- packages/searchkit/src/___tests___/functional/__snapshots__/KNNSearch.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/getQuery.test.ts.snap
- packages/searchkit/src/___tests___/functional/getQuery.test.ts
- packages/searchkit/src/transformRequest.ts
- packages/searchkit/src/types.ts
- yarn.lock
Much better support for KNN
```ts
const results = await client.handleRequest(req.body, {
getKnnQuery(query, search_attributes, config) {
return {
field: 'dense-vector-field',
k: 10,
num_candidates: 100,
// supported in latest version of Elasticsearch
query_vector_builder: { 
text_embedding: {
model_id: 'cookie_model',
model_text: query
}
}
}
}
});
```
> KNN Support

- apps/web/pages/autocomplete.jsx
- apps/web/pages/camping-sites-demo.jsx
- apps/web/pages/demo-ecommerce.tsx
- apps/web/pages/demo.tsx
- apps/web/pages/docs/getting-started/with-react.mdx
- apps/web/pages/docs/overview.mdx
- apps/web/pages/docs/tutorials/with-nextjs.mdx
- apps/web/pages/geo-search-demo.jsx
- examples/with-ui-nextjs-react/app/api/search/route.ts
- examples/with-ui-nextjs-react/app/layout.tsx
- examples/with-ui-nextjs-react/app/page.tsx
- examples/with-ui-nextjs-react/pages/_app.tsx
this updates the tutorial to show examples using the app router instead of the "legacy" pages router.
> Improve nextjs tutorial

- apps/web/pages/docs/overview.mdx
missing `docs` in the original mdx.
> fix searchkit with Availability Search tutorial url

- .changeset/bright-points-explode.md
- packages/searchkit/src/___tests___/filters.test.ts
- packages/searchkit/src/filters.ts
Adds support to floating point numeric filters such to be used in instantsearch queries such as:
```
{
numericFilters: [
"total_amount >= 7.13",
"total_amount<=7.29"
]
}
```
The approach used was to improve the digit selector `\d+` in the regex to the following:`(?:\d+(?:\.\d*)?|\.\d+)`, allowing to match number such as `100.2`, 100.` and `1.`. This ensures support for:
- Numbers with a decimal part (e.g., 100.2)
- Whole numbers ending with a decimal (e.g., 100.)
- Numbers with a leading decimal point and a fractional part (e.g., .1)
The updated pattern incorporates non-capturing groups, indicated by the usage of ?:. This approach ensures that this change integrates with the existing logic without requiring further alterations.
> add support to floating point numeric filters

- packages/searchkit/src/Transporter.ts
- packages/searchkit/src/___tests___/functional/Transporter.browser.test.ts
- packages/searchkit/src/___tests___/functional/Transporter.test.ts
Searchkit was sending "application/json" to the search engine API, this is technically incorrect, since the body of the request is a list of jsons concatenated by newline. This breaks the parsing of the request body on some (proxy) servers, for example Ruby on Rails, since when it tries to parse a json, if finds it is broken.
This fixes #1360.
> Change content-type from json to x-ndjson (sent by searchkit to the search engine API)

- .changeset/cold-grapes-change.md
- apps/web/pages/docs/proxy-elasticsearch/with-your-own-server.mdx
- packages/searchkit/src/Transporter.ts
- packages/searchkit/src/___tests___/functional/Transporter.browser.test.ts
- packages/searchkit/src/___tests___/functional/Transporter.test.ts
Impacting servers which dont honour the nd-json type. Switching back to this and adding documentation to note you can override the content type via `CustomTransporter` or providing the content-type via headers option.
> Switch to json content type

- packages/searchkit/src/filters.ts
I'm sorry but somehow I missed one line in the code in #1395 where it is also necessary to replace the parameter for `split`.
> Complete support colons in facet values

- apps/web/pages/docs/api-documentation/searchkit.mdx
The path `/docs/guides/facets/` doesn't exist (yet) so it's better to link a sub-page than to have a link leading to a kind of 404 page.
> Fix link in documentation

- apps/web/pages/docs/api-documentation/searchkit.mdx
- packages/searchkit/src/transformRequest.ts
- packages/searchkit/src/types.ts
We have a few sites where we would like to tweak the fuzziness slightly. This is currently not possible as it is hardcoded. By adding this into the config, we can tweak this.
I'm not sure if this would be the best place to actually put it but I couldn't find anything that would be better.
> Allow fuzziness to be configured
