searchkit/searchkit

- src/components/search/search-box/src/SearchBox.tsx
- src/components/search/search-box/test/SearchboxSpec.tsx
> SearchBox : fix throttle

- src/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter.tsx
- src/components/search/filters/numeric-refinement-list-filter/styles/index.scss
- src/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec.tsx
> NumericRefinementListFilter : hide when empty

- src/__test__/core/react/SearchkitComponentSpec.tsx
- src/components/search/hits/src/Hits.tsx
- src/components/search/hits/src/InitialLoader.tsx
- src/components/search/hits/test/HitsSpec.tsx
- src/components/search/search-box/src/SearchBox.tsx
- src/components/search/search-box/test/SearchboxSpec.tsx
- src/core/react/ReactComponentType.ts
- src/core/react/SearchkitComponent.ts
add searchThrottleTime
update hits component to itemComponent
surpress translation warning
> #55 #17 #43

- src/components/search/filters/refinement-list-filter/test/RefinementListFilterSpec.tsx
Adds test for itemComponent and component props
> RefinementListFilter tests

- src/components/index.ts
- src/components/search/filters/filter-item/src/FilterItem.tsx
- src/components/search/filters/menu-filter/src/MenuFilter.tsx
- src/components/search/filters/menu-filter/test/MenuFilterSpec.tsx
- src/components/search/filters/refinement-list-filter/src/RefinementListFilter.tsx
- src/components/search/filters/refinement-list-filter/test/RefinementListFilterSpec.tsx
- tsconfig.json
> MenuFilter + RefinementListFilter item functional component #68

- src/__test__/core/SearchkitManagerSpec.ts
- src/__test__/core/react/SearchkitComponentSpec.tsx
- src/core/SearchkitManager.ts
- src/core/react/SearchkitComponent.ts
> add hits change detect

- docs/components/sorting/sort.md
- src/__test__/core/accessors/SortingAccessorSpec.ts
- src/components/search/sorting-selector/src/SortingSelector.tsx
- src/components/search/sorting-selector/test/SortSelectorSpec.tsx
- src/core/accessors/SortingAccessor.ts
> fix the sorting component, add defaultOption field

- src/__test__/core/AccessorManagerSpec.ts
- src/__test__/core/accessors/AccessorSpec.ts
- src/core/AccessorManager.ts
- src/core/accessors/Accessor.ts
> fix accessor remove

- src/__test__/core/accessors/FacetAccessorSpec.ts
- src/__test__/core/accessors/StatefulAccessorSpec.ts
- src/__test__/core/support/UtilsSpec.ts
- src/components/search/filters/menu-filter/test/MenuFilterSpec.tsx
- src/components/search/filters/refinement-list-filter/test/RefinementListFilterSpec.tsx
- src/core/accessors/FacetAccessor.ts
- src/core/accessors/StatefulAccessor.ts
- src/core/support/Utils.ts
> namespace facet aggregators, simplify Utils.guid

- docs/components/navigation/hierarchical-menu.md
- docs/components/navigation/menu.md
- docs/components/navigation/refinement-list.md
- src/__test__/core/accessors/FacetAccessorSpec.ts
- src/__test__/core/accessors/HierarchicalFacetAccessorSpec.ts
- src/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter.tsx
- src/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec.tsx
- src/components/search/filters/menu-filter/src/MenuFilter.tsx
- src/components/search/filters/menu-filter/test/MenuFilterSpec.tsx
- src/components/search/filters/refinement-list-filter/src/RefinementListFilter.tsx
- src/components/search/filters/refinement-list-filter/test/RefinementListFilterSpec.tsx
- src/core/accessors/FacetAccessor.ts
- src/core/accessors/HierarchicalFacetAccessor.ts
> Facet sorting

- docs/components/navigation/reset.md
- src/components/search/filters/reset-filters/src/ResetFilters.tsx
- src/components/search/filters/reset-filters/test/ResetFiltersSpec.tsx
> add back query for backwards compat

- CHANGELOG.md
- src/components/search/pagination/src/Pagination.tsx
- src/components/search/pagination/test/PaginationSpec.tsx
> fix pagination

- CHANGELOG.md
- src/__test__/core/accessors/FacetAccessorSpec.ts
- src/components/search/filters/refinement-list-filter/test/RefinementListFilterSpec.tsx
- src/core/accessors/FacetAccessor.ts
> fix view more regression

- docs/components/sorting/sort.md
- src/__test__/core/accessors/SortingAccessorSpec.ts
- src/components/search/sorting-selector/src/SortingSelector.tsx
- src/components/search/sorting-selector/test/SortSelectorSpec.tsx
- src/core/accessors/SortingAccessor.ts
> Make SortSelector handle no field, order properties

- docs/core/SearchkitManager.md
- src/__test__/core/SearchRequestSpec.ts
- src/__test__/core/SearchkitManagerSpec.ts
- src/core/SearchRequest.ts
- src/core/SearchkitManager.ts
> add queryProcessor

- docs/components/navigation/menu.md
- docs/components/navigation/refinement-list.md
- src/components/search/filters/menu-filter/src/MenuFilter.tsx
- src/components/search/filters/menu-filter/test/MenuFilterSpec.tsx
- src/components/search/filters/refinement-list-filter/src/RefinementListFilter.tsx
- src/components/search/filters/refinement-list-filter/test/RefinementListFilterSpec.tsx
> Add include + exclude to Facet components

- docs/core/Architecture.md
Components can have multiple references to Accessors
> Graph updated

- src/components/search/filters/input-filter/InputFilter.tsx
- src/components/search/filters/input-filter/InputFilter.unit.tsx
- src/core/accessors/QueryAccessor.ts
- test/e2e/server/apps/playground/TogglePanel.tsx
- tsconfig.json
Forked SearchBox into a custom input filter, handles disabled state much better.
Added tests
> InputFilter tests and improvements

- src/components/search/filters/input-filter/InputFilter.tsx
- src/components/search/filters/input-filter/InputFilter.unit.tsx
- theming/components/_input-filter.scss
> add InputFilter remove cross

- src/components/search/pagination/src/Pagination.tsx
- src/components/search/pagination/test/PaginationSpec.tsx
> Pagination fix

- src/__test__/core/accessors/RangeAccessorSpec.ts
- src/components/search/filters/range-filter/src/RangeFilter.tsx
- src/components/search/filters/range-filter/test/RangeFilterSpec.tsx
- src/core/accessors/RangeAccessor.ts
- test/e2e/server/apps/movie-app/index.tsx
- tsconfig.json
> RangeFilter to support Histogram=false option 

- docs/theming/using-searchkit-theme.md
- src/components/ui/layout/Layout.tsx
- src/components/ui/layout/Layout.unit.tsx
- theming/theme.scss
- tsconfig.json
> Update theme docs

- src/components/search/filters/input-filter/InputFilter.tsx
- src/components/search/filters/input-filter/InputFilter.unit.tsx
- src/components/search/search-box/SearchBox.tsx
- src/components/search/search-box/Searchbox.unit.tsx
- src/core/accessors/QueryAccessor.ts
- test/e2e/server/apps/playground/index.tsx
> [WIP] InputFilter blurAction

- src/__test__/core/accessors/NumericalOptionsAccessorSpec.ts
- src/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter.tsx
- src/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec.tsx
- src/core/accessors/NumericOptionsAccessor.ts
fixes #259
Added NumericalOptionsAccessor.getDocCount()
> Switch from key to uuid in NumericalOptionsAccessor aggregator

- theming/components/_range-input.scss
> range-input css improvements

- src/__test__/core/accessors/DynamicRangeAccessorSpec.ts
- src/core/accessors/DynamicRangeAccessor.ts
> ceil / floor min max values for dynamicRangeAccessor

- src/components/search/filters/facet-filter/MenuFilter.tsx
- src/components/search/filters/facet-filter/MenuFilter.unit.tsx
> MenuFilter all fix

- docs/README.md
- docs/components/navigation/menu.md
- docs/components/navigation/numeric-refinement-list.md
- docs/components/navigation/range-filter.md
- docs/components/navigation/refinement-list.md
- docs/core/FieldOptions.md
- src/__test__/core/query/field_context/ChildrenFieldContext.unit.ts
- src/__test__/core/query/field_context/NestedFieldContext.unit.ts
- src/__test__/core/query/query_dsl/joining/HasChildQuerySpec.ts
- src/__test__/core/query/query_dsl/joining/HasParentQuerySpec.ts
- src/__test__/core/query/query_dsl/joining/NestedQuerySpec.ts
- src/core/query/field_context/ChildrenFieldContext.ts
- src/core/query/field_context/NestedFieldContext.ts
- src/core/query/query_dsl/joining/HasChildQuery.ts
- src/core/query/query_dsl/joining/HasParentQuery.ts
- src/core/query/query_dsl/joining/NestedQuery.ts
> Support additional nested/child query options

- docs/components/metadata/stats.md
- docs/components/navigation/hierarchical-menu.md
- docs/components/navigation/hierarchical-refinement-filter.md
- docs/components/navigation/menu.md
- docs/components/navigation/numeric-refinement-list.md
- docs/components/navigation/refinement-list.md
- src/components/search/filters/facet-filter/FacetFilter.tsx
- src/components/search/filters/facet-filter/FacetFilter.unit.tsx
- src/components/search/filters/facet-filter/FacetFilterProps.ts
- src/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter.tsx
- src/components/search/filters/hierarchical-menu-filter/test/HierarchicalMenuFilterSpec.tsx
- src/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter.tsx
- src/components/search/filters/hierarchical-refinement-filter/test/HierarchicalRefinementFilterSpec.tsx
- src/components/search/filters/numeric-refinement-list-filter/src/NumericRefinementListFilter.tsx
- src/components/search/filters/numeric-refinement-list-filter/test/NumericRefinementListFilterSpec.tsx
- src/components/search/hits-stats/src/HitsStats.tsx
- src/components/search/hits-stats/test/HitsStatsSpec.tsx
- src/components/ui/list/ItemHistogramList.tsx
- src/components/ui/list/ItemHistogramList.unit.tsx
- src/components/ui/list/ItemListComponents.tsx
- src/components/ui/list/ItemListComponents.unit.tsx
- src/components/ui/list/ListProps.ts
- src/components/ui/list/MockList.tsx
- src/components/ui/list/Select.tsx
- src/components/ui/list/Select.unit.tsx
- src/components/ui/list/TagCloud.tsx
- src/components/ui/list/TagCloud.unit.tsx
- test/e2e/server/apps/list-app/index.tsx
- test/e2e/server/apps/playground/index.tsx
> WIP countFormatter

- src/__test__/core/accessors/DynamicRangeAccessorSpec.ts
- src/__test__/core/accessors/HierarchicalFacetAccessorSpec.ts
- src/__test__/core/accessors/NestedFacetAccessorSpec.ts
- src/__test__/core/accessors/NumericalOptionsAccessorSpec.ts
- src/__test__/core/accessors/RangeAccessorSpec.ts
- src/__test__/core/query/ImmutableQuerySpec.ts
- src/core/query/ImmutableQuery.ts
use post_filter instead of filter, to be compatible with es5 + older es
> make filter es5 compat

- src/__test__/core/query/query_dsl/joining/NestedQuerySpec.ts
- src/core/query/query_dsl/joining/NestedQuery.ts
> Fixes parsing exception: [nested] query does not support  (#413 )

- docs/components/metadata/stats.md
cf `HitsStats.tsx`
```javascript
render() {
const timeTaken = this.searchkit.getTime()
const {countFormatter} = this.props
const hitsCount = countFormatter(this.searchkit.getHitsCount())
const props: HitsStatsDisplayProps = {
bemBlocks:this.bemBlocks,
translate:this.translate,
timeTaken: timeTaken,
hitsCount: hitsCount,
resultsFoundLabel: this.translate("hitstats.results_found", {
timeTaken:timeTaken,
hitCount:hitsCount /* here */
})
}
return renderComponent(this.props.component, props)
}
```
> docs(stats): update translation

- docs/components/navigation/selected-filters.md
`{props.labelKey)}` => `{props.labelKey}`
> Remove typo in selected-filters.md

- src/__test__/core/query/ImmutableQuerySpec.ts
- src/__test__/core/query/query_dsl/compound/BoolQueriesSpec.ts
- src/core/query/query_dsl/compound/BoolQueries.ts
> BoolQueries handle non array values

- docs/core/QueryDSL.md
- src/__test__/core/query/query_dsl/term_level/ExistsQuerySpec.ts
- src/core/query/query_dsl/term_level/ExistsQuery.ts
- src/core/query/query_dsl/term_level/index.ts
> Add exists query

- packages/searchkit-e2e-tests/cypress/integration/movie_spec.js
- packages/searchkit-e2e-tests/cypress/integration/taxonomy_spec.js
- packages/searchkit/package-lock.json
- packages/searchkit/src/components/search/filters/hierarchical-menu-filter/src/HierarchicalMenuFilter.tsx
- packages/searchkit/src/components/search/filters/hierarchical-menu-filter/test/__snapshots__/HierarchicalMenuFilterSpec.tsx.snap
- packages/searchkit/src/components/search/filters/hierarchical-refinement-filter/src/HierarchicalRefinementFilter.tsx
- packages/searchkit/src/components/search/filters/hierarchical-refinement-filter/test/__snapshots__/HierarchicalRefinementFilterSpec.tsx.snap
- Use Panel as containerComponent
- Use ItemComponent
- allows standards, but also reuse/customisation
> Standardise Hierarchical components

- packages/searchkit/src/components/display/view-switcher/ViewSwitcherConfig.ts
- packages/searchkit/src/components/display/view-switcher/ViewSwitcherHits.tsx
Added pull request just in case since I had the code changes locally. Hope this is good.
> Update definitions for array declaration in props.

- packages/searchkit/theming/theme.scss
- packages/searchkit/theming/vars.scss
As per issue #664 add the ability to theme the searchbox text color and placeholder color
> Add the ability to theme the searchbox colors

- packages/searchkit/src/components/search/filters/facet-filter/MenuFilter.tsx
> Remove duplicated export

- packages/searchkit/src/__test__/core/SearchkitManagerSpec.ts
- packages/searchkit/src/core/SearchkitManager.ts
Fixes #696
Fixes #698
Fixes #717 
Fixes #732
Related to #718
> Fix hits count retrieving on ES7

- docs/docs/guides-graphql-schema.md
- docs/docs/searchkit-apollo-resolvers.md
- packages/searchkit-apollo-resolvers/src/schema.ts
- packages/searchkit-apollo-resolvers/tests/FacetResolver.test.ts
> fix: facet size can be configured / changed at query time

- docs/docs/ui-setup-own-components.md
syntax error fixed for searchInput
> syntax error in ui-setup-own-components.md

- CHANGELOG.md
- docs/docs/guides-indexing.md
- examples/indexer/config.ts
- examples/indexer/skConfig.md
- examples/next/pages/api/graphql.js
- lerna.json
- package.json
- packages/searchkit-apollo-resolvers/CHANGELOG.md
- packages/searchkit-apollo-resolvers/package.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-cli/src/index.ts
- packages/searchkit-cli/src/lib.ts
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
lib was not being built prior to publishing. issue was the build step wasn't scoped in
> fix(searchkit/cli): fix issue with cli not working

- CHANGELOG.md
- docs/docs/customisations-adding-base-filters.md
- docs/docs/guides-indexing.md
- docs/docs/searchkit-schema.md
- docs/sidebars.js
- examples/next/pages/api/graphql.js
- lerna.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
- packages/searchkit-schema/CHANGELOG.md
- packages/searchkit-schema/package.json
- packages/searchkit-schema/src/core/SearchkitRequest.ts
- packages/searchkit-schema/src/core/__tests__/SearchkitRequest.test.ts
- packages/searchkit-schema/src/query/BaseQuery.ts
- packages/searchkit-schema/src/query/CustomQuery.ts
- packages/searchkit-schema/src/query/MultiMatchQuery.ts
- packages/searchkit-schema/src/query/__tests__/CustomQuery.test.ts
- packages/searchkit-schema/src/resolvers/ResultsResolver.ts
- packages/searchkit-schema/src/schema.ts
- packages/searchkit-schema/tests/BaseFilters.test.ts
- packages/searchkit-schema/tests/Customisations.test.ts
- packages/searchkit-schema/tests/FacetResolver.test.ts
- packages/searchkit-schema/tests/FacetsResolver.test.ts
- packages/searchkit-schema/tests/HitsResolver.test.ts
- packages/searchkit-schema/tests/SummaryResolver.test.ts
- packages/searchkit-schema/tests/__snapshots__/BaseFilters.test.ts.snap
> Base Filters Functionality

- packages/searchkit-e2e-tests/package.json
- packages/searchkit-e2e-tests/src/apps/movie-app/index.tsx
- packages/searchkit-refinement-autosuggest/package.json
- packages/searchkit/package.json
- yarn.lock
> chore(css-loader): bump css-loader

- docs/docs/searchkit-schema.md
- packages/searchkit-schema/src/core/FacetsFns.ts
- packages/searchkit-schema/src/core/SearchkitRequest.ts
- packages/searchkit-schema/src/query/BaseQuery.ts
- packages/searchkit-schema/src/query/CustomQuery.ts
- packages/searchkit-schema/src/query/MultiMatchQuery.ts
- packages/searchkit-schema/src/query/__tests__/CustomQuery.test.ts
- packages/searchkit-schema/tests/BaseFilters.test.ts
- packages/searchkit-schema/tests/Customisations.test.ts
- packages/searchkit-schema/tests/FacetResolver.test.ts
- packages/searchkit-schema/tests/FacetsResolver.test.ts
- packages/searchkit-schema/tests/GeoFilters.test.ts
- packages/searchkit-schema/tests/HitsResolver.test.ts
- packages/searchkit-schema/tests/SummaryResolver.test.ts
> breaking: full es query control from Query interfaces

- CHANGELOG.md
- lerna.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
- packages/searchkit-schema/CHANGELOG.md
- packages/searchkit-schema/package.json
> chore: release rc28

- packages/searchkit-client/src/__tests__/searchkit.test.tsx
- packages/searchkit-client/src/searchkit.tsx
- packages/searchkit-schema/src/facets/DateRangeFacet.ts
- packages/searchkit-schema/src/facets/RangeFacet.ts
- packages/searchkit-schema/tests/RangeFilters.test.ts
- packages/searchkit-schema/tests/__snapshots__/RangeFilters.test.ts.snap
> feat(rangefilter): allow min / max & dateMin / dateMax to be optional

- packages/searchkit-cli/src/lib.ts
This edition works with 7.12.0
> Changed type , and mapping

- CHANGELOG.md
- lerna.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
- packages/searchkit-schema/CHANGELOG.md
- packages/searchkit-schema/package.json
*Features*
- Highlighting https://searchkit.co/docs/guides/highlighting-fields
- Url Synchronisation https://searchkit.co/docs/guides/url-synchronization
- Server side rendering support https://searchkit.co/docs/guides/ssr-server-side-rendering
- Searchkit Variables hook https://searchkit.co/docs/reference/searchkit-client#usesearchkitvariables-hook
> Release 31

- docs/docs/guides-ssr.md
- docs/docs/searchkit-client.md
- docs/src/pages/index.js
- examples/next/hocs/withApollo.js
- examples/next/pages/ssr-example.jsx
- packages/searchkit-client/src/__tests__/components.test.tsx
- packages/searchkit-client/src/__tests__/withSearchkitRouting.test.tsx
- packages/searchkit-client/src/components.tsx
- packages/searchkit-client/src/history.ts
- packages/searchkit-client/src/index.ts
- packages/searchkit-client/src/searchkit.tsx
- packages/searchkit-client/src/withSearchkitRouting.tsx
- packages/searchkit-elastic-ui/src/Facets/ListFacet/index.tsx
- Fix: Applying Filters from url synchronisation to the search
- Feat: Allows developer to customise the url via createURL / parseURL
- Feat: PaginationLink & FilterLink components which provide hrefs and api calls to handle onClick
> Url sync with filters + Filter / Pagination Link Components for SEO

- .github/workflows/cd.yml
issue where the node-version argument is incorrect.
> update cd node version

- docs/docs/base-ui-setup.md
Split into two code blocks to avoid confusion with that being a single file
> Code style

- CHANGELOG.md
- README.md
- docs/docs/customisations-add-new-facet.md
- docs/docs/customisations-adding-base-filters.md
- docs/docs/customisations-custom-query.md
- docs/docs/customisations-logging.md
- lerna.json
- packages/searchkit-cli/CHANGELOG.md
- packages/searchkit-cli/package.json
- packages/searchkit-client/CHANGELOG.md
- packages/searchkit-client/package.json
- packages/searchkit-elastic-ui/CHANGELOG.md
- packages/searchkit-elastic-ui/package.json
- packages/searchkit-schema/CHANGELOG.md
- packages/searchkit-schema/package.json
- packages/searchkit-schema/src/core/SearchkitRequest.ts
- packages/searchkit-schema/src/core/__tests__/SearchkitRequest.test.ts
> #1040 Simplify logging out the Elasticsearch query via env flag

- packages/searchkit-schema/src/core/SearchkitRequest.ts
- packages/searchkit-schema/src/core/__tests__/SearchkitRequest.test.ts
- packages/searchkit-schema/tests/__mock-data__/FacetResolver/Facet.json
- packages/searchkit-schema/tests/facets/FacetResolver.test.ts
See https://github.com/searchkit/searchkit/issues/1043 for more details
> fix (1043) Fix facet node to be able to specify multiple times in one query

- docs/docs/searchkit-sdk.md
- packages/searchkit-schema/src/resolvers/ResultsResolver.ts
- packages/searchkit-sdk/src/index.ts
- packages/searchkit-sdk/src/transformers/index.ts
- packages/searchkit-sdk/tests/hits.test.ts
noticed in SDK I do not return the rawHit. PR to fix this https://github.com/searchkit/searchkit/issues/1102
> include raw hit in @searchkit/schema

- .eslintrc
- docs/docs/searchkit-sdk-grouping.mdx
- packages/searchkit-schema/tests/__snapshots__/HitsResolver.test.ts.snap
- packages/searchkit-sdk/package.json
- packages/searchkit-sdk/src/core/FacetsFns.ts
- packages/searchkit-sdk/src/core/QueryManager.ts
- packages/searchkit-sdk/src/core/RequestBodyBuilder.ts
- packages/searchkit-sdk/src/core/__tests__/FacetsFns.test.ts
- packages/searchkit-sdk/src/index.ts
- packages/searchkit-sdk/src/transformers/index.ts
- packages/searchkit-sdk/tests/__mock-data__/collapse/Hits.json
- packages/searchkit-sdk/tests/__snapshots__/BaseFilters.test.ts.snap
- packages/searchkit-sdk/tests/__snapshots__/collapse.test.ts.snap
- packages/searchkit-sdk/tests/__snapshots__/hits.test.ts.snap
- packages/searchkit-sdk/tests/__snapshots__/postProcessRequest.test.ts.snap
- packages/searchkit-sdk/tests/__snapshots__/sortBy.test.ts.snap
- packages/searchkit-sdk/tests/collapse.test.ts
- packages/searchkit-sdk/tests/filters-facets/__snapshots__/baseFilters.test.ts.snap
- yarn.lock
> Collapse / Field Grouping support

- .changeset/pre.json
- .changeset/strong-toes-burn.md
- apps/web/CHANGELOG.md
- apps/web/package.json
- apps/web/pages/api/search.ts
- apps/web/pages/docs/guides/facets.mdx
- apps/web/public/sitemap-0.xml
- packages/searchkit-api/CHANGELOG.md
- packages/searchkit-api/package.json
- packages/searchkit-api/src/___tests___/functional/__snapshots__/nestedFacets.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/getFilters.test.ts
- packages/searchkit-api/src/___tests___/functional/getQuery.test.ts
- packages/searchkit-api/src/___tests___/functional/index.test.ts
- packages/searchkit-api/src/___tests___/functional/nestedFacets.test.ts
- packages/searchkit-api/src/___tests___/functional/queryRules.test.ts
- packages/searchkit-api/src/___tests___/functional/relevance.test.ts
- packages/searchkit-api/src/___tests___/mocks/AlgoliaRequests.ts
- packages/searchkit-api/src/___tests___/mocks/ElasticsearchResponses.ts
- packages/searchkit-api/src/___tests___/transformRequest.test.ts
- packages/searchkit-api/src/___tests___/utils.test.ts
- packages/searchkit-api/src/transformRequest.ts
- packages/searchkit-api/src/transformResponse.ts
- packages/searchkit-api/src/types.ts
- packages/searchkit-api/src/utils.ts
> support for nested fields for facets and filters

- .changeset/healthy-queens-breathe.md
- packages/searchkit-api/package.json
- packages/searchkit-api/src/___tests___/functional/__snapshots__/nestedFacets.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/nestedFacets.test.ts
- packages/searchkit-api/src/___tests___/mocks/ElasticsearchResponses.ts
- packages/searchkit-api/src/transformRequest.ts
Fixes issue where has 2 or more facets which share the same nested path.
> Fix mixed nested facets

- .changeset/long-dodos-marry.md
- .changeset/pre.json
- apps/web/CHANGELOG.md
- apps/web/package.json
- apps/web/pages/docs/api-documentation/api.mdx
- apps/web/pages/docs/getting-started/index.mdx
- apps/web/public/sitemap-0.xml
- packages/searchkit-api/CHANGELOG.md
- packages/searchkit-api/package.json
- packages/searchkit-api/src/Transporter.ts
- packages/searchkit-api/src/___tests___/functional/TransportErrors.test.ts
- packages/searchkit-api/src/___tests___/functional/__snapshots__/TransportErrors.test.ts.snap
- packages/searchkit-api/src/___tests___/mocks/ErrorElasticsearchResponses.ts
- packages/searchkit-api/src/index.ts
- packages/searchkit-api/src/transformResponse.ts
- packages/searchkit-api/src/types.ts
> Better error debug support

- .changeset/tricky-bugs-compete.md
- apps/web/pages/docs/api-documentation/api.mdx
- apps/web/pages/docs/guides/connecting-to-elasticsearch.mdx
- packages/searchkit-api/src/Transporter.ts
- packages/searchkit-api/src/___tests___/functional/Transporter.test.ts
- packages/searchkit-api/src/___tests___/functional/index.test.ts
- packages/searchkit-api/src/types.ts
Allow custom headers to be provided in connection settings
> V4: add custom headers support for connection

- .changeset/cold-foxes-camp.md
- apps/web/pages/api/search.ts
- packages/searchkit-api/src/___tests___/functional/queryRules.test.ts
- packages/searchkit-api/src/transformRequest.ts
- packages/searchkit-api/src/transformResponse.ts
> V4: Query Rules - Fix query rewrite

- .changeset/nasty-clocks-learn.md
- packages/searchkit-api/src/___tests___/functional/__snapshots__/hitsPerPage.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/__snapshots__/index.test.ts.snap
- packages/searchkit-api/src/___tests___/functional/hitsPerPage.test.ts
- packages/searchkit-api/src/transformRequest.ts
- packages/searchkit-api/src/transformResponse.ts
hitsPerPage = 0 is used when only facets are requested.
> Fix handle hitsPerPage = 0

- .changeset/ten-mirrors-taste.md
- apps/web/pages/api/search.ts
- apps/web/pages/docs/guides/facets.mdx
- apps/web/pages/docs/guides/query-rules.mdx
- packages/searchkit-api/src/___tests___/functional/getQuery.test.ts
- packages/searchkit-api/src/___tests___/functional/queryRules.test.ts
- packages/searchkit-api/src/___tests___/functional/relevance.test.ts
- packages/searchkit-api/src/___tests___/getSatisfiedRules.test.ts
- packages/searchkit-api/src/types.ts
Add ID attribute to QueryRule Type
> Add ID attribute to QueryRule Type

- .changeset/bright-baboons-tickle.md
- apps/web/pages/api/product-search.ts
- apps/web/pages/api/search.ts
- apps/web/pages/demo-ecommerce.tsx
- apps/web/pages/demo.tsx
- apps/web/pages/docs/api-documentation/api.mdx
- apps/web/pages/docs/guides/_meta.json
- apps/web/pages/docs/guides/sorting.mdx
- apps/web/styles.css
- apps/web/tailwind.config.js
- packages/searchkit-api/src/___tests___/functional/sorting.test.ts
- packages/searchkit-api/src/index.ts
- packages/searchkit-api/src/sorting.ts
- packages/searchkit-api/src/transformRequest.ts
- packages/searchkit-api/src/types.ts
This adds sorting support to v4
closes #1197
> V4: Sorting Support

- .changeset/happy-dolphins-fetch.md
- .changeset/twelve-goats-happen.md
- packages/searchkit-api/test/__snapshots__/exports.test.ts.snap
- packages/searchkit-instantsearch-client/src/index.ts
- packages/searchkit-instantsearch-client/test/__snapshots__/browserOnly.test.ts.snap
- packages/searchkit/package.json
- packages/searchkit/src/___tests___/functional/__snapshots__/filters.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/getFilters.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/getQuery.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/hitsPerPage.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/hooks.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/index.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/nestedFacets.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/queryRules.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/relevance.test.ts.snap
- packages/searchkit/src/transformResponse.ts
- packages/searchkit/tsup.config.js
this allows developers to use searchkit via CDN scripts
> Umd searchkit

- .changeset/pink-keys-smell.md
- apps/web/pages/node-proxy-demo.jsx
- packages/searchkit-instantsearch-client/src/index.ts
- packages/searchkit/src/___tests___/functional/__snapshots__/nestedFacetQuery.test.ts.snap
- packages/searchkit/src/___tests___/functional/nestedFacetQuery.test.ts
- packages/searchkit/src/___tests___/mocks/AlgoliaRequests.ts
- packages/searchkit/src/___tests___/mocks/ElasticsearchResponses.ts
- packages/searchkit/src/transformResponse.ts
fixes https://github.com/searchkit/searchkit/issues/1210
> Fix nested facet query

- .changeset/strange-pumpkins-type.md
- apps/web/next.config.js
- apps/web/package.json
- apps/web/pages/demos.mdx
- apps/web/pages/docs/api-documentation/searchkit.mdx
- apps/web/pages/docs/guides/_meta.json
- apps/web/pages/docs/guides/geo-search.mdx
- apps/web/pages/geo-search-demo.jsx
- packages/searchkit/src/___tests___/functional/__snapshots__/geoFilters.test.ts.snap
- packages/searchkit/src/___tests___/functional/geoFilters.test.ts
- packages/searchkit/src/___tests___/mocks/AlgoliaRequests.ts
- packages/searchkit/src/___tests___/mocks/ElasticsearchResponses.ts
- packages/searchkit/src/filters.ts
- packages/searchkit/src/transformRequest.ts
- packages/searchkit/src/transformResponse.ts
- packages/searchkit/src/types.ts
- yarn.lock
fixes #1196. The Facet option will be built once custom facet hooks are implemented.
> Geo filtering capability

- .changeset/config.json
- .changeset/weak-berries-tap.md
- examples/with-express-javascript-esm/package.json
- examples/with-ui-instantsearchjs/.gitignore
- examples/with-ui-instantsearchjs/README.md
- examples/with-ui-instantsearchjs/index.html
- examples/with-ui-instantsearchjs/package.json
- examples/with-ui-instantsearchjs/src/main.ts
- examples/with-ui-instantsearchjs/src/style.css
- examples/with-ui-instantsearchjs/src/vite-env.d.ts
- examples/with-ui-instantsearchjs/tsconfig.json
- packages/searchkit/package.json
- packages/searchkit/src/Transporter.ts
- packages/searchkit/src/___tests___/functional/Transporter.browser.test.ts
- packages/searchkit/src/types.ts
- yarn.lock
fixes https://github.com/searchkit/searchkit/issues/1235
> fix auth issue on browser

- .changeset/popular-dryers-reflect.md
- apps/web/pages/docs/getting-started/with-javascript.mdx
- apps/web/pages/docs/getting-started/with-react.mdx
- apps/web/pages/docs/guides/customising-query.mdx
- apps/web/pages/docs/proxy-elasticsearch/with-cloudflare-workers.mdx
- apps/web/pages/docs/proxy-elasticsearch/with-express-js.mdx
- apps/web/pages/docs/proxy-elasticsearch/with-next-js.mdx
- apps/web/pages/docs/tutorials/build-availability-search-ui.mdx
- apps/web/pages/docs/tutorials/with-nextjs.mdx
- examples/with-cloudflare-workers/src/index.ts
- examples/with-express-javascript-cjs/index.js
- examples/with-express-javascript-esm/index.js
- examples/with-express-typescript-cjs/src/index.ts
- examples/with-express-typescript-esm/src/index.ts
- examples/with-ui-instantsearchjs/src/main.ts
- examples/with-ui-nextjs-react/pages/api/search.ts
- examples/with-ui-vue/src/App.vue
- packages/searchkit/src/Transporter.ts
- packages/searchkit/src/___tests___/functional/__snapshots__/TransportErrors.test.ts.snap
- Add better documentation for authentication
- Add better error messaging for auth issues
- fix the KNN Search example
> Add better auth dx

- .changeset/famous-years-doubt.md
- .changeset/tall-kangaroos-divide.md
- apps/web/pages/docs/api-documentation/searchkit.mdx
- examples/with-ui-nextjs-react/pages/api/search.ts
- examples/with-ui-nextjs-react/pages/index.tsx
- packages/searchkit/src/___tests___/functional/__snapshots__/customFiltersFacets.test.ts.snap
- packages/searchkit/src/___tests___/functional/__snapshots__/filters.test.ts.snap
- packages/searchkit/src/___tests___/functional/customFiltersFacets.test.ts
- packages/searchkit/src/___tests___/functional/filters.test.ts
- packages/searchkit/src/filterUtils.ts
- packages/searchkit/src/filters.ts
- packages/searchkit/src/index.ts
- packages/searchkit/src/transformRequest.ts
- packages/searchkit/src/types.ts
- packages/searchkit/src/utils.ts
fixes https://github.com/searchkit/searchkit/issues/1174
> Custom facet and filter support

- apps/web/pages/docs/api-documentation/searchkit.mdx
- apps/web/pages/docs/components/results/snippet.mdx
- packages/searchkit/src/___tests___/functional/snippetAttributes.test.ts
- packages/searchkit/src/highlightUtils.ts
- packages/searchkit/src/transformRequest.ts
- packages/searchkit/src/types.ts
> Add SearchSettingsConfig setting for custom snippet length

- .changeset/eight-swans-push.md
- examples/with-ui-nextjs-react/pages/api/search.ts
- packages/searchkit/src/___tests___/functional/snippetAttributes.test.ts
- packages/searchkit/src/___tests___/mocks/ElasticsearchResponses.ts
- packages/searchkit/src/highlightUtils.ts
- packages/searchkit/src/transformRequest.ts
> 4.6.1 fix snippet length feature

- packages/searchkit/src/___tests___/highlightUtils.test.ts
- packages/searchkit/src/highlightUtils.ts
> feat: add support for wildcards in `highlight_attributes` configuration

- .changeset/violet-dingos-work.md
- apps/web/package.json
- apps/web/pages/autocomplete.jsx
- apps/web/pages/docs/components/autocomplete.mdx
- packages/searchkit-instantsearch-client/package.json
- packages/searchkit-instantsearch-client/src/index.ts
- yarn.lock
Removed spoofing transporter so it doesn't rely on their cache interface to hydrate the frontend
> Fix issue with 7.2.0+ for SSR with nextjs

- .changeset/tiny-frogs-shake.md
- .github/workflows/test.yml
- .vscode/launch.json
- DEVELOPMENT.md
- apps/web/pages/demo.tsx
- packages/searchkit-api/package.json
- packages/searchkit/package.json
- packages/searchkit/src/___tests___/functional/highlightAttributes.test.ts
- packages/searchkit/src/___tests___/highlightUtils.test.ts
- packages/searchkit/src/___tests___/mocks/AlgoliaRequests.ts
- packages/searchkit/src/___tests___/mocks/ElasticsearchResponses.ts
- packages/searchkit/src/highlightUtils.ts
- yarn.lock
fixes https://github.com/searchkit/searchkit/issues/1343
> Fix object field highlighting

- .changeset/seven-dogs-camp.md
- apps/web/pages/docs/api-documentation/searchkit.mdx
- packages/searchkit/src/Transporter.ts
- packages/searchkit/src/___tests___/functional/Transporter.test.ts
- packages/searchkit/src/___tests___/functional/__snapshots__/TransportErrors.test.ts.snap
- packages/searchkit/src/types.ts
added optional credentials based on ConfigConnection.withCredentials
> added withCredentials parameters to ConfigConnection

- packages/searchkit/src/___tests___/highlightUtils.test.ts
- packages/searchkit/src/highlightUtils.ts
> Add logic to retrieve the field value when fieldKey is dot-notation

- .changeset/fluffy-walls-report.md
- packages/searchkit-instantsearch-client/src/index.ts
fixes https://github.com/searchkit/searchkit/issues/1388
> Instantsearch Client Adapter - change type to any for type mismatches in future

- README.md
Gen AI chatbot for Searchkit. Will help Developers understand this repository better. You can ask for code examples, installation guide, debugging help and much more.
> Add Searchkit AI Bot in Readme

- packages/searchkit/src/queryRules.ts
This allows to use colons as separator and the use of URLs and concerns issue #1260.
> Support colons in facet values

- apps/web/pages/docs/components/sort-by.mdx
- packages/searchkit/src/___tests___/functional/sorting.test.ts
- packages/searchkit/src/sorting.ts
- packages/searchkit/src/types.ts
- Added support for nested field sorting and array field sorting modes in the documentation.
- Updated sorting configuration to include `nestedPath` and `mode` parameters for better handling of complex data structures.
- Enhanced the `SortingOption` type definition to reflect new sorting capabilities.
- Added integration tests for sorting on nested fields and multiple sort criteria.
> feat: Enhance sorting functionality in documentation and code
